Repository Duelers/Duelers, pull requests merged in 2020-03, with the labels that each got.

#263 Fixed card stuttering ingame on every action
  Client/src/main/java/org/projectcardboard/client/view/battleview/CardAnimation.java
  Client/src/main/java/org/projectcardboard/client/view/battleview/HandBox.java
Labels: improvement, low priority, ui

#245 nerf + text change
  Server/resources/accounts/duelyst.account.json
  Server/resources/minionCards/SpectralRevenant.minion.card.json
  devTools/cardCreator/cards_to_import/SpectralRevenant.minion.card.json
  resources/minionCards/SpectralRevenant.minion.card.json
Labels: Game Balance, improvement

#240 Fix on counterattack
  Server/resources/accounts/duelyst.account.json
  Server/resources/minionCards/CelestialPhantom.minion.card.json
  Server/resources/minionCards/SunSeer.minion.card.json
  Server/src/server/gameCenter/models/game/Game.java
  devTools/cardCreator/cards_to_import/CelestialPhantom.minion.card.json
  devTools/cardCreator/cards_to_import/SunSeer.minion.card.json
  resources/minionCards/CelestialPhantom.minion.card.json
  resources/minionCards/SunSeer.minion.card.json
Labels: bug, good first issue, improvement

#243 Fix dying wish
  Client/src/main/resources/troopAnimations/neutral_masteroftheseven.plist.json
  Server/resources/accounts/duelyst.account.json
  Server/resources/minionCards/Sellsoul.minion.card.json
  Server/src/server/gameCenter/models/game/Game.java
  devTools/cardCreator/cards_to_import/Sellsoul.minion.card.json
  resources/minionCards/Sellsoul.minion.card.json
Labels: bug, improvement

#310 Fixed the case in which cards would stay grey / coloured.
  Client/src/main/java/org/projectcardboard/client/view/battleview/HandBox.java
Labels: bug, ui

#329 moved bat to build_exe, since this folder makes the most sense
  Build_exe/bat/CardBoardLogger.bat
  Build_exe/bat/CardBoardLogger.lnk
Labels: Developer

#328 Blatm cards
  devTools/cardCreator/cards_to_import/Broken/Crossbones.minion.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/BeastboundSavage.minion.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/DarkTransformation.spell.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/Elucidator.minion.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/LysianBrawler.minion.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/MakantorWarbeast.minion.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/Orizuru.minion.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/Phalanxar.minion.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/SoulshatterPact.spell.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/Terradon.minion.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/WarSurge.spell.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/YoungFlamewing.minion.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/_Readme.txt
Labels: content

#340 Card phalanxar
  Client/src/main/resources/troopAnimations/f5_tank.plist.json
  Server/resources/accounts/duelyst.account.json
  Server/resources/minionCards/Phalanxar.minion.card.json
  Server/resources/spellCards/Fireball.spell.card.json
  devTools/cardCreator/cards_to_import/Fireball.spell.card.json
  devTools/cardCreator/cards_to_import/NonDuelyst/Fireball.spell.card.json
  devTools/cardCreator/cards_to_import/Phalanxar.minion.card.json
  resources/minionCards/Phalanxar.minion.card.json
Labels: content

#331 Fix replace bug where replacing a card into empty deck gives NPE
  Client/src/main/java/org/projectcardboard/client/models/game/availableactions/AvailableActions.java
  Server/src/server/gameCenter/models/game/Player.java
Labels: bug

#369 Add wait cursor on log and register
  Client/src/main/java/org/projectcardboard/client/models/gui/DeckCardsGrid.java
  Client/src/main/java/org/projectcardboard/client/models/gui/DialogBox.java
  Client/src/main/java/org/projectcardboard/client/models/gui/LoginFieldsContainer.java
  Client/src/main/java/org/projectcardboard/client/models/gui/OrangeButton.java
  Client/src/main/java/org/projectcardboard/client/view/ErrorView.java
  Client/src/main/java/org/projectcardboard/client/view/GlobalChatDialog.java
Labels: improvement, ui

#371 add mute button
  Client/src/main/java/org/projectcardboard/client/controller/SoundEffectPlayer.java
  Client/src/main/java/org/projectcardboard/client/view/battleview/PlayerBox.java
Labels: improvement, low priority, new feature, ui

#354 Update AvailableActions.java
  Client/src/main/java/org/projectcardboard/client/models/game/availableactions/AvailableActions.java
Labels: bug

#370 Display mana in numerical form
  Client/src/main/java/org/projectcardboard/client/view/battleview/PlayerBox.java
Labels: improvement, ui

#381 balance
  Server/resources/accounts/duelyst.account.json
  Server/resources/minionCards/AymaraHealer.minion.card.json
  Server/resources/minionCards/SaberspineTiger.minion.card.json
  Server/resources/spellCards/VoidPulse.spell.card.json
  devTools/cardCreator/cards_to_import/AymaraHealer.minion.card.json
  devTools/cardCreator/cards_to_import/SaberspineTiger.minion.card.json
  devTools/cardCreator/cards_to_import/VoidPulse.spell.card.json
  resources/minionCards/AymaraHealer.minion.card.json
  resources/minionCards/SaberspineTiger.minion.card.json
  resources/spellCards/VoidPulse.spell.card.json
Labels: Game Design/Balance

#330 Deck Size: min = 5, max = 40
  Server/src/test/java/Deck_Test.java
  Shared/src/shared/models/card/BaseDeck.java
Labels: Developer, Game Design/Balance

#383 add ghost l to pending cards
  Client/src/main/resources/icons/icon_f2_ghost_lightning.plist.json
  Client/src/main/resources/icons/icon_f2_ghost_lightning.png
  devTools/cardCreator/cards_to_import/NeedValidationChecks/GhostLightning.spell.card.json
Labels: content

#395 Build exe
  .gitignore
  devTools/CardBoardLogger.bat
  devTools/build_exe/CardBoard.bat
  devTools/build_exe/PackageExe.py
  devTools/build_exe/release/.gitkeep
Labels: Developer

#399 Implemented a turn timer.
  Client/src/main/java/org/projectcardboard/client/view/battleview/HandBox.java
Labels: improvement, ui

#401 Fixed the formatting being modifed on saveAccount
  Server/resources/accounts/duelyst.account.json
  Server/resources/accounts/template.account.json
  Server/src/server/clientPortal/models/JsonConverter.java
  Server/src/server/dataCenter/DataCenter.java
Labels: bug

#402 Remove unused done message from client and server
  Client/src/main/java/org/projectcardboard/client/controller/Client.java
  Client/src/main/java/org/projectcardboard/client/models/message/MessageType.java
  Server/src/server/GameServer.java
  Server/src/server/clientPortal/models/message/Message.java
  Server/src/server/clientPortal/models/message/MessageType.java
  Server/src/server/dataCenter/DataCenter.java
Labels: Developer, improvement, low priority

#418 Add makantor
  Client/src/main/resources/troopAnimations/f5_mankatorwarbeast.plist.json
  Client/src/main/resources/troopAnimations/f5_mankatorwarbeast.png
  Server/resources/accounts/duelyst.account.json
  Server/resources/minionCards/MakantorWarbeast.minion.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/MakantorWarbeast.minion.card.json
  resources/minionCards/MakantorWarbeast.minion.card.json
Labels: content, good first issue

#417 Add beastmaster
  Client/src/main/resources/troopAnimations/neutral_beastmaster.plist.json
  Client/src/main/resources/troopAnimations/neutral_beastmaster.png
  Server/resources/accounts/duelyst.account.json
  Server/resources/minionCards/BeastboundSavage.minion.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/BeastboundSavage.minion.card.json
  resources/minionCards/BeastboundSavage.minion.card.json
Labels: content, good first issue

#416 Add orizuru
  Client/src/main/resources/troopAnimations/f2_orizuru.plist.json
  Client/src/main/resources/troopAnimations/f2_orizuru.png
  Server/resources/accounts/duelyst.account.json
  Server/resources/minionCards/Orizuru.minion.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/Orizuru.minion.card.json
  resources/minionCards/Orizuru.minion.card.json
Labels: content, good first issue

#414 add card "arms race"
  Client/src/main/resources/icons/icon_f1_enthrall.plist.json
  Client/src/main/resources/icons/icon_f1_enthrall.png
  devTools/cardCreator/cards_to_import/NeedValidationChecks/ArmsRace.spell.card.json
Labels: content, good first issue

#412 cards Dark transform
  Client/src/main/resources/icons/icon_f4_darktransformation.plist.json
  Client/src/main/resources/icons/icon_f4_darktransformation.png
  Server/resources/accounts/duelyst.account.json
  Server/resources/spellCards/DarkTransformation.spell.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/DarkTransformation.spell.card.json
  resources/spellCards/DarkTransformation.spell.card.json
Labels: content, good first issue

#411 Add ghost l
  Server/resources/accounts/duelyst.account.json
  Server/resources/spellCards/GhostLightning.spell.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/GhostLightning.spell.card.json
  resources/spellCards/GhostLightning.spell.card.json
Labels: content, good first issue

#388 Display mana in numerical form
  Client/src/main/java/org/projectcardboard/client/view/battleview/PlayerBox.java
Labels: improvement, low priority, ui

#410 add card (burden)
  Client/src/main/resources/icons/icon_f3_glimpse.plist.json
  Client/src/main/resources/icons/icon_f3_glimpse.png
  devTools/cardCreator/cards_to_import/NeedValidationChecks/BurdenofKnowledge.spell.card.json
Labels: content, good first issue

#422 Add arms race
  Server/resources/accounts/duelyst.account.json
  Server/resources/spellCards/ArmsRace.spell.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/ArmsRace.spell.card.json
  resources/spellCards/ArmsRace.spell.card.json
Labels: content

#421 Add burden
  Server/resources/accounts/duelyst.account.json
  Server/resources/spellCards/BurdenofKnowledge.spell.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/BurdenofKnowledge.spell.card.json
  resources/spellCards/BurdenofKnowledge.spell.card.json
Labels: content

#427 Completely remove all mention of next card
  Client/src/main/java/org/projectcardboard/client/controller/Client.java
  Client/src/main/java/org/projectcardboard/client/controller/GameController.java
  Client/src/main/java/org/projectcardboard/client/models/card/Deck.java
  Client/src/main/java/org/projectcardboard/client/models/compresseddata/CompressedGame.java
  Client/src/main/java/org/projectcardboard/client/models/game/GameActions.java
  Client/src/main/java/org/projectcardboard/client/models/game/Player.java
  Client/src/main/java/org/projectcardboard/client/models/message/CardPosition.java
  Client/src/main/java/org/projectcardboard/client/models/message/Message.java
  Client/src/main/java/org/projectcardboard/client/models/message/MessageType.java
  Server/src/server/GameServer.java
  Server/src/server/clientPortal/models/message/Message.java
  Server/src/server/clientPortal/models/message/MessageType.java
  Server/src/server/gameCenter/GameCenter.java
  Server/src/server/gameCenter/models/game/Game.java
  Server/src/server/gameCenter/models/game/Player.java
  Server/src/server/gameCenter/models/game/availableActions/Attack.java
  Shared/src/shared/models/game/BasePlayer.java
  Shared/src/test/java/models/game/BasePlayer_Test.java
  Shared/src/test/java/models/game/map/BaseGameMap_Test.java
Labels: Developer, improvement

#431 update-all-user's-card-collection-when-server-has-new-cards
  Server/src/server/dataCenter/DataCenter.java
  Server/src/server/dataCenter/models/account/Account.java
  Server/src/server/dataCenter/models/account/Collection.java
Labels: Developer, improvement

#438 Add server name to Login Screen
  Client/src/main/java/org/projectcardboard/client/view/LoginMenu.java
Labels: Developer, good first issue

#445 Add Komodo Charger
  Client/src/main/resources/troopAnimations/neutral_beastcavern.plist.json
  Client/src/main/resources/troopAnimations/neutral_beastcavern.png
  devTools/cardCreator/cards_to_import/NeedValidationChecks/KomodoCharger.minion.card.json
Labels: content

#444 Add Rogue Warden
  Client/src/main/resources/troopAnimations/f1_ranged.plist.json
  Client/src/main/resources/troopAnimations/f1_ranged.png
  devTools/cardCreator/cards_to_import/NeedValidationChecks/RogueWarden.minion.card.json
Labels: content

#441 Add cards to v.queue
  Client/src/main/resources/icons/icon_f1_circleoflife.plist.json
  Client/src/main/resources/icons/icon_f1_circleoflife.png
  Client/src/main/resources/icons/icon_f3_circleofdessication.plist.json
  Client/src/main/resources/icons/icon_f3_circleofdessication.png
  Client/src/main/resources/icons/icon_f5_flamingstampede.plist.json
  Client/src/main/resources/icons/icon_f5_flamingstampede.png
  devTools/cardCreator/cards_to_import/NeedValidationChecks/CircleOfLife.spell.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/CircleofDessication.spell.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/FlamingStampede.spell.card.json
Labels: content

#433 Draining Wave -- add card to validation queue
  Client/src/main/resources/icons/icon_f1_drainingwave.plist.json
  Client/src/main/resources/icons/icon_f1_drainingwave.png
  devTools/cardCreator/cards_to_import/NeedValidationChecks/DrainingWave.spell.card.json
Labels: content

#432 Card peacekeeper -- add card to validation queue
  Client/src/main/resources/troopAnimations/f1_peacekeeper.plist.json
  Client/src/main/resources/troopAnimations/f1_peacekeeper.png
  devTools/cardCreator/cards_to_import/NeedValidationChecks/Peacekeeper.minion.card.json
Labels: content

#447 add to val q
  Client/src/main/resources/troopAnimations/neutral_mercazurehorn.plist.json
  Client/src/main/resources/troopAnimations/neutral_mercazurehorn.png
  devTools/cardCreator/cards_to_import/NeedValidationChecks/AzureHornShaman.minion.card.json
Labels: content

#436 Fix replace into same card issue
  Server/src/server/gameCenter/models/game/Game.java
  Server/src/server/gameCenter/models/game/Player.java
  Shared/src/shared/models/card/Card.java
Labels: bug, improvement

#462 Fix greyed out card after replace bug
  Client/src/main/java/org/projectcardboard/client/controller/Client.java
  Client/src/main/java/org/projectcardboard/client/models/game/Player.java
Labels: bug

#429 Add/Fix counterattack ability
  Server/resources/accounts/duelyst.account.json
  Server/resources/minionCards/CelestialPhantom.minion.card.json
  Server/resources/minionCards/SpectralRevenant.minion.card.json
  Server/resources/minionCards/SunSeer.minion.card.json
  Server/src/server/gameCenter/models/game/Game.java
  Shared/src/shared/models/card/spell/AvailabilityType.java
  devTools/cardCreator/cards_to_import/CelestialPhantom.minion.card.json
  devTools/cardCreator/cards_to_import/SpectralRevenant.minion.card.json
  devTools/cardCreator/cards_to_import/SunSeer.minion.card.json
  resources/minionCards/CelestialPhantom.minion.card.json
  resources/minionCards/SpectralRevenant.minion.card.json
  resources/minionCards/SunSeer.minion.card.json
Labels: bug, improvement

#449 add card komodo charger
  Server/resources/accounts/duelyst.account.json
  Server/resources/minionCards/KomodoCharger.minion.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/KomodoCharger.minion.card.json
  resources/minionCards/KomodoCharger.minion.card.json
Labels: content

#450 Add card circle of life
  Server/resources/accounts/duelyst.account.json
  Server/resources/spellCards/CircleOfLife.spell.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/CircleOfLife.spell.card.json
  resources/spellCards/CircleOfLife.spell.card.json
Labels: content

#451 Add card draining wave
  Server/resources/accounts/duelyst.account.json
  Server/resources/spellCards/DrainingWave.spell.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/DrainingWave.spell.card.json
  resources/spellCards/DrainingWave.spell.card.json
Labels: content

#453 add card flaming stampede
  Server/resources/accounts/duelyst.account.json
  Server/resources/spellCards/FlamingStampede.spell.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/FlamingStampede.spell.card.json
  resources/spellCards/FlamingStampede.spell.card.json
Labels: content

#454 Add card rogue warden
  Client/src/main/resources/troopAnimations/f1_ranged.plist.json
  Server/resources/accounts/duelyst.account.json
  Server/resources/minionCards/RogueWarden.minion.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/RogueWarden.minion.card.json
  resources/minionCards/RogueWarden.minion.card.json
Labels: content

#452 add card dessication
  Server/resources/accounts/duelyst.account.json
  Server/resources/spellCards/CircleofDessication.spell.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/CircleofDessication.spell.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/RogueWarden.minion.card.json
  resources/spellCards/CircleofDessication.spell.card.json
Labels: content

#430 Add validation for single target spells
  Client/src/main/java/org/projectcardboard/client/models/game/availableactions/AvailableActions.java
  Client/src/main/java/org/projectcardboard/client/view/battleview/Constants.java
  Client/src/main/java/org/projectcardboard/client/view/battleview/MapBox.java
  Server/src/server/dataCenter/models/card/ServerCard.java
  Server/src/server/gameCenter/models/game/Game.java
  Server/src/server/gameCenter/models/game/Player.java
  Shared/src/shared/models/card/Card.java
  Shared/src/shared/models/card/spell/Spell.java
Labels: bug, improvement

#471 Show opponents hand and deck size
  Client/src/main/java/org/projectcardboard/client/view/battleview/PlayerBox.java
Labels: improvement, new feature, ui

#473 improve method of checking if player has up to date collection
  Server/src/server/dataCenter/DataCenter.java
  Server/src/server/dataCenter/models/account/Collection.java
Labels: Developer, improvement

#456 Add card peacekeeper
  Client/src/main/resources/troopAnimations/f1_peacekeeper.plist.json
  Server/resources/accounts/duelyst.account.json
  Server/resources/minionCards/Peacekeeper.minion.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/Peacekeeper.minion.card.json
  resources/minionCards/Peacekeeper.minion.card.json
Labels: DO NOT MERGE, content

#478 Update .gitignore
  .gitignore
Labels: Developer

#482 Fix multiple replaces bug
  Client/src/main/java/org/projectcardboard/client/view/battleview/HandBox.java
  Server/src/server/gameCenter/models/game/Game.java
Labels: bug

#484 Card Dagger Kiri
  Client/src/main/resources/troopAnimations/neutral_mercdaggerkiri.plist.json
  Client/src/main/resources/troopAnimations/neutral_mercdaggerkiri.png
  devTools/cardCreator/cards_to_import/NeedValidationChecks/DaggerKiri.minion.card.json
Labels: content

#486 Balance change (spiral, aymara)
  Server/resources/accounts/duelyst.account.json
  Server/resources/minionCards/AymaraHealer.minion.card.json
  Server/resources/spellCards/SpiralTechnique.spell.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/AymaraHealer.minion.card.json
  devTools/cardCreator/cards_to_import/SpiralTechnique.spell.card.json
  resources/minionCards/AymaraHealer.minion.card.json
  resources/spellCards/SpiralTechnique.spell.card.json
Labels: Game Design/Balance

#487 Add Card Kiri
  .gitignore
  Client/src/main/resources/troopAnimations/neutral_mercdaggerkiri.plist.json
  Server/resources/accounts/duelyst.account.json
  Server/resources/minionCards/DaggerKiri.minion.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/DaggerKiri.minion.card.json
  resources/minionCards/DaggerKiri.minion.card.json
Labels: content, good first issue

#455 Add card azure shaman
  Client/src/main/resources/troopAnimations/neutral_mercazurehorn.plist.json
  Server/resources/accounts/duelyst.account.json
  Server/resources/minionCards/AzureHornShaman.minion.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/AzureHornShaman.minion.card.json
  resources/minionCards/AzureHornShaman.minion.card.json
Labels: DO NOT MERGE, content

#489 Add Primus Shieldmaster to Validation queue
  Client/src/main/resources/troopAnimations/neutral_primusshieldmaster.plist.json
  Client/src/main/resources/troopAnimations/neutral_primusshieldmaster.png
  devTools/cardCreator/cards_to_import/NeedValidationChecks/PrimusShieldmaster.minion.card.json
Labels: content, good first issue

#490 Make jfile chooser default to exported decks folder
  Client/src/main/java/org/projectcardboard/client/Constants.java
  Client/src/main/java/org/projectcardboard/client/models/card/DeckExporter.java
  Client/src/main/java/org/projectcardboard/client/view/CollectionMenu.java
Labels: New Player Experience, improvement

#488 Fx on each spell
  Client/src/main/java/org/projectcardboard/client/controller/GameController.java
  Client/src/main/java/org/projectcardboard/client/models/message/SpellAnimation.java
  Client/src/main/java/org/projectcardboard/client/view/battleview/BattleScene.java
  Client/src/main/resources/fx/fx_slashfrenzy.plist.json
  Client/src/main/resources/fx/fx_slashfrenzy.png
  Server/resources/minionCards/MakantorWarbeast.minion.card.json
  Server/resources/minionCards/Peacekeeper.minion.card.json
  Server/resources/minionCards/PiercingMantis.minion.card.json
  Server/resources/minionCards/Serpenti.minion.card.json
  Server/resources/minionCards/WarTalon.minion.card.json
  Server/src/server/GameServer.java
  Server/src/server/clientPortal/models/message/GameAnimations.java
  Server/src/server/clientPortal/models/message/Message.java
  Server/src/server/clientPortal/models/message/SpellAnimation.java
  Server/src/server/gameCenter/models/game/Game.java
  Shared/src/shared/models/card/spell/Spell.java
  devTools/cardCreator/cards_to_import/MakantorWarbeast.minion.card.json
  devTools/cardCreator/cards_to_import/Peacekeeper.minion.card.json
  devTools/cardCreator/cards_to_import/PiercingMantis.minion.card.json
  devTools/cardCreator/cards_to_import/Serpenti.minion.card.json
  devTools/cardCreator/cards_to_import/WarTalon.minion.card.json
  resources/minionCards/MakantorWarbeast.minion.card.json
  resources/minionCards/Peacekeeper.minion.card.json
  resources/minionCards/PiercingMantis.minion.card.json
  resources/minionCards/Serpenti.minion.card.json
  resources/minionCards/WarTalon.minion.card.json
Labels: content

#505 Add Katara
  Client/src/main/resources/troopAnimations/f2_katara.plist.json
  Client/src/main/resources/troopAnimations/f2_katara.png
  devTools/cardCreator/cards_to_import/NeedValidationChecks/Katara.minion.card.json
Labels: content, good first issue

#506 Add Scarlet Viper
  Client/src/main/resources/troopAnimations/f2_support.plist.json
  Client/src/main/resources/troopAnimations/f2_support.png
  devTools/cardCreator/cards_to_import/NeedValidationChecks/ScarletViper.minion.card.json
Labels: content, good first issue

#504 New card rush celerity backstab
  Client/src/main/resources/troopAnimations/f2_buildcommon.plist.json
  Client/src/main/resources/troopAnimations/f2_buildcommon.png
  Server/resources/accounts/duelyst.account.json
  Server/resources/minionCards/Hashishi.minion.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/Hashishi.minion.card.json
  resources/minionCards/Hashishi.minion.card.json
Labels: content, good first issue

#503 Add gorehorn
  Client/src/main/resources/troopAnimations/f2_tank.plist.json
  Client/src/main/resources/troopAnimations/f2_tank.png
  Server/resources/accounts/duelyst.account.json
  Server/resources/minionCards/GoreHorn.minion.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/GoreHorn.minion.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/GoreHorn.minion.card.json
  resources/minionCards/GoreHorn.minion.card.json
Labels: content, good first issue

#507 Add viper
  Client/src/main/resources/troopAnimations/f2_support.plist.json
  Server/resources/accounts/duelyst.account.json
  Server/resources/minionCards/ScarletViper.minion.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/NeedValidationChecks/GoreHorn.minion.card.json
  devTools/cardCreator/cards_to_import/ScarletViper.minion.card.json
  resources/minionCards/ScarletViper.minion.card.json
Labels: content, good first issue

#518 Add Sand Carved Juggernaut
  Client/src/main/resources/troopAnimations/f3_windstriker.plist.json
  Client/src/main/resources/troopAnimations/f3_windstriker.png
  devTools/cardCreator/cards_to_import/NeedValidationChecks/SandCarvedJuggernaut.minion.card.json
Labels: content

#519 Add Gnasher
  Client/src/main/resources/troopAnimations/neutral_gnasher.plist.json
  Client/src/main/resources/troopAnimations/neutral_gnasher.png
  devTools/cardCreator/cards_to_import/NeedValidationChecks/Gnasher.minion.card.json
Labels: content

#511 New generals validation q
  Client/src/main/resources/photo/doghai_portrait.png
  Client/src/main/resources/photo/general_portrait_image_hex_f3@2x.png
  Client/src/main/resources/photo/general_portrait_image_hex_f4@2x.png
  Client/src/main/resources/troopAnimations/f1_caliber-o.plist.json
  Client/src/main/resources/troopAnimations/f1_caliber-o.png
  Server/resources/accounts/duelyst.account.json
  Server/resources/minionCards/DragonLark.minion.card.json
  Server/resources/minionCards/Hashishi.minion.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/Dragonlark.minion.card.json
  devTools/cardCreator/cards_to_import/Hashishi.minion.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/Calibero.hero.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/CassyvaSoulreaper.hero.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/Goodboi.hero.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/LilitheBlightchaser.hero.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/ScionessSajj.hero.card.json
  devTools/cardCreator/cards_to_import/NeedValidationChecks/ZirixStarstrider.hero.card.json
  resources/minionCards/DragonLark.minion.card.json
  resources/minionCards/Hashishi.minion.card.json
Labels: content

#493 add support to update user config file
  Client/src/main/java/org/projectcardboard/client/Main.java
  Server/src/Config/Config.java
  Server/src/main/resources/config.properties
Labels: Developer, improvement, new feature

#477 Varying resolution support
  Client/src/main/java/org/projectcardboard/client/controller/GraphicalUserInterface.java
  Client/src/main/java/org/projectcardboard/client/models/gui/UIConstants.java
  Client/src/main/java/org/projectcardboard/client/view/battleview/Constants.java
  Server/src/main/resources/config.properties
Labels: new feature, ui

#517 Factions2
  Client/src/main/java/org/projectcardboard/client/models/gui/CardDetailBox.java
  Client/src/main/java/org/projectcardboard/client/models/gui/CardPane.java
  Client/src/main/java/org/projectcardboard/client/models/gui/DeckBox.java
  Client/src/test/java/org/projectcardboard/client/models/gui/DeckBox_Test.java
  Server/src/server/dataCenter/DataCenter.java
  Server/src/server/dataCenter/models/card/ServerCard.java
  Server/src/test/java/AvailableActions_Test.java
  Server/src/test/java/Deck_Test.java
  Shared/src/shared/UtilityFunctions.java
  Shared/src/shared/models/card/Card.java
  Shared/src/shared/models/card/ICard.java
  Shared/src/test/java/models/game/UtilityFunctions_Test.java
Labels: content, improvement, new feature

#527 add nomad scout
  Client/src/main/resources/troopAnimations/f3_buildcommon.plist.json
  Client/src/main/resources/troopAnimations/f3_buildcommon.png
  devTools/cardCreator/cards_to_import/NonDuelyst/NomadScout.minion.card.Json
Labels: content, good first issue

#533 Add custom card support
  Client/src/main/java/org/projectcardboard/client/models/gui/ImageLoader.java
  Client/src/main/java/org/projectcardboard/client/view/battleview/CardAnimation.java
  Client/src/main/java/org/projectcardboard/client/view/battleview/MapBox.java
  Client/src/main/java/org/projectcardboard/client/view/battleview/SpellAnimation.java
  Client/src/main/java/org/projectcardboard/client/view/battleview/TroopAnimation.java
  Server/resources/accounts/duelyst.account.json
  Server/src/Config/Config.java
  Server/src/main/resources/config.properties
  Server/src/server/dataCenter/DataCenter.java
  Server/src/server/dataCenter/models/card/ServerCard.java
  Server/src/test/java/AvailableActions_Test.java
  Server/src/test/java/Deck_Test.java
  Shared/src/shared/UtilityFunctions.java
  Shared/src/shared/models/card/Card.java
  Shared/src/shared/models/card/ICard.java
Labels: documentation, improvement, new feature
