Repository Duelers/Duelers, pull requests merged in 2020-04, with the labels that each got.

#557 Starterdecks
  .gitignore
  devTools/build_exe/PackageExe.py
  exported_decks/Aggro_starter_deck.deck.json
  exported_decks/Golem_starter_deck.deck.json
Labels: Developer, New Player Experience, content, good first issue, low priority

#555 Add Support To Left/Right Click Cards To Add/Remove Cards From Your Deck
  Client/src/main/java/org/projectcardboard/client/models/gui/DeckCardsGrid.java
Labels: documentation, improvement, ui

#558 fix-0-cost-sufficient-mana-bug
  Client/src/main/java/org/projectcardboard/client/models/game/availableactions/AvailableActions.java
  Server/src/server/gameCenter/models/game/Player.java
  Server/src/server/gameCenter/models/game/availableActions/AvailableActions.java
Labels: bug

#567 Lyonar expansion
  Client/src/main/resources/fx/fx_buff.plist.json
  Client/src/main/resources/fx/fx_f1_inmolation.plist.json
  Client/src/main/resources/fx/fx_f1_inmolation.png
  Client/src/main/resources/fx/fx_heavenlystrike.plist.json
  Client/src/main/resources/icons/icon_f1_chargeintobattle.plist.json
  Client/src/main/resources/icons/icon_f1_chargeintobattle.png
  Client/src/main/resources/icons/icon_f1_holyimmolation.plist.json
  Client/src/main/resources/icons/icon_f1_holyimmolation.png
  Client/src/main/resources/icons/icon_f1_laststand.plist.json
  Client/src/main/resources/icons/icon_f1_laststand.png
  Client/src/main/resources/troopAnimations/boss_dissonance.plist.json
  Client/src/main/resources/troopAnimations/boss_dissonance.png
  Client/src/main/resources/troopAnimations/f1_gryphinox.plist.json
  Client/src/main/resources/troopAnimations/f1_gryphinox.png
  Client/src/main/resources/troopAnimations/f1_invincibuddy.plist.json
  Client/src/main/resources/troopAnimations/f1_invincibuddy.png
  Client/src/main/resources/troopAnimations/f1_kingsguard.plist.json
  Client/src/main/resources/troopAnimations/f1_kingsguard.png
  Client/src/main/resources/troopAnimations/f1_leovoyant.plist.json
  Client/src/main/resources/troopAnimations/f1_leovoyant.png
  Client/src/main/resources/troopAnimations/f1_silverguardsquire.plist.json
  Client/src/main/resources/troopAnimations/f1_silverguardsquire.png
  Client/src/main/resources/troopAnimations/f1_sunforgelancer.plist.json
  Client/src/main/resources/troopAnimations/f1_sunforgelancer.png
  Client/src/main/resources/troopAnimations/f1_tank.plist.json
  Client/src/main/resources/troopAnimations/f1_tank.png
  Server/resources/minionCards/Eminence.minion.card.json
  Server/resources/minionCards/SanctifiedHawk.minion.card.json
  Server/resources/minionCards/SilentDevotee.minion.card.json
  Server/resources/minionCards/SilverguardKnight.minion.card.json
  Server/resources/minionCards/SilverguardSquire.minion.card.json
  Server/resources/minionCards/SunfuryLancer.minion.card.json
  Server/resources/minionCards/SunsightDeacon.minion.card.json
  Server/resources/minionCards/SunsightInquisitor.minion.card.json
  Server/resources/spellCards/BurningZealotry.spell.card.json
  Server/resources/spellCards/HolyImmolation.spell.card.json
  Server/resources/spellCards/Oration.spell.card.json
  devTools/cardCreator/card_list.csv
  devTools/cardCreator/cards_to_import/BurningZealotry.spell.card.json
  devTools/cardCreator/cards_to_import/Eminence.minion.card.json
  devTools/cardCreator/cards_to_import/HolyImmolation.spell.card.json
  devTools/cardCreator/cards_to_import/Oration.spell.card.json
  devTools/cardCreator/cards_to_import/SanctifiedHawk.minion.card.json
  devTools/cardCreator/cards_to_import/SilentDevotee.minion.card.json
  devTools/cardCreator/cards_to_import/SilverguardKnight.minion.card.json
  devTools/cardCreator/cards_to_import/SilverguardSquire.minion.card.json
  devTools/cardCreator/cards_to_import/SunfuryLancer.minion.card.json
  devTools/cardCreator/cards_to_import/SunsightDeacon.minion.card.json
  devTools/cardCreator/cards_to_import/SunsightInquisitor.minion.card.json
  resources/minionCards/Eminence.minion.card.json
  resources/minionCards/SanctifiedHawk.minion.card.json
  resources/minionCards/SilentDevotee.minion.card.json
  resources/minionCards/SilverguardKnight.minion.card.json
  resources/minionCards/SilverguardSquire.minion.card.json
  resources/minionCards/SunfuryLancer.minion.card.json
  resources/minionCards/SunsightDeacon.minion.card.json
  resources/minionCards/SunsightInquisitor.minion.card.json
  resources/spellCards/BurningZealotry.spell.card.json
  resources/spellCards/HolyImmolation.spell.card.json
  resources/spellCards/Oration.spell.card.json
Labels: content
